### PR TITLE
Feature fix search function

### LINKED ISSUE #11: Search bar should seach name OR ingredient on current page
input: string into the search bar

- [x] refactor single return to accept multiple conditions
- [x] push recipes that pass conditions to an array
- [x] add test for ingredient
- [x] fix tests as they had a bad path for the data

output: all recipes where the string is included in the name OR ingredient

### PR DESCRIPTION
**Pull request by mattdeann**
**What does this PR do?**
Completes desired functionality for recipe search bar

**What does it fix?**
The search bar was returning only recipes where the name held the queried string. The single return function searchRecipes() now returns both name and ingredient matches.

**Is this a feature or a fix?**
This is a fix, as the function was half working.

**Where should the reviewer start?**
All changes were made in the scripts.js file, under the searchRecipes() function

**How should this be tested?**
Search queries will now return both name matches and ingredient matches!

**Do you have any questions or issues about this addition?**

- [x] Did you test your code locally first?
- [x] Does this follow our intended guidelines (DRY & commented) for project code?

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -256,9 +256,38 @@ function pressEnterSearch(event) {
 
 function searchRecipes() {
   showAllRecipes();
-  let searchedRecipes = recipeData.filter(recipe => {
-    return recipe.name.toLowerCase().includes(searchInput.value.toLowerCase());
+  let searchedRecipes = [];
+
+
+
+  recipeData.forEach(recipe => {
```
Comment (rachelbuchta) [inline src/scripts.js:263]: This looks good, Matt! I do think as we work through all of this more, we will be able to do some refactoring as well as move this function to be come a method in the recipe class and call it in scripts.js.

File: src/scripts.js [hunk 2]
```diff
@@ -256,9 +256,38 @@ function pressEnterSearch(event) {
...
+  //     searchedRecipes.push(recipe);
+  //   }
+
+  //   recipe.ingredients.forEach(ingredient => {
+  //     if (ingredient.name.toLowerCase().includes(searchInput.value.toLowerCase())) {
+  //       searchedRecipes.push(recipe);
+  //     }
+  //   })
+  // })
+  console.log(searchedRecipes);
```
Comment (rachelbuchta) [inline src/scripts.js:289]: I'm wondering if this needs to be a return instead of a console.log
